image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --activate-profiles headless -DskipUiTests=true"

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository/
  key: "$CI_BUILD_REF_NAME"

build:
  stage: build
  script:
    - cd time-master; mvn clean install $MAVEN_CLI_OPTS

test:
  stage: test
  coverage: '/Total.*?([0-9]{1,3})%/'
  script:
    - cd time-master; mvn clean test $MAVEN_CLI_OPTS
    - cd ../
    - ls
    - cd time-master
    - ls
    - cd coverage
    - ls -a
    # - cd target
    # - ls
    # - cd site
    # - ls
    # - cd jacoco-aggregate
    # - ls
    # - cat coverage/target/site/jacoco-aggregate/index.html | grep -o '<tfoot>.*</tfoot>'
    
