image: maven:3.8.6

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  $MAVEN_CLI_OPTS: "--batch-mode --activate-profiles -DskipUiTests=true"

stages:
  - build


cache:
  paths:
    - .m2/repository/
    - target/

test:
  stage: test
  script:
    - "cd time-master; mvn clean test $MAVEN_CLI_OPTS"

build:
  stage: build
  when: manual
  script:
    - "cd time-master; mvn clean install $MAVEN_CLI_OPTS"
