image: maven:3.8.6

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Djava.awt.headless=true"
  $MAVEN_CLI_OPTS: "--batch-mode --activate-profiles headless -DskipUiTests=true"

stages:
  - build
  - test


cache:
  paths:
    - .m2/repository/
  key: "$CI_BUILD_REF_NAME"

build:
  stage: build
  when: manual
  script:
    - "cd time-master; mvn clean install $MAVEN_CLI_OPTS"

test:
  stage: test
  script:
    - "cd time-master; mvn clean test $MAVEN_CLI_OPTS"


