@startuml Time Master

package "docs" as docs

    package "diagrams" as diagrams
    package "img"
    package "release1"
    package "release2"

package "time-master"

    package "core"

        package "src"
            package "main"
                 package "test"

            package "timeMaster"

        package "target"
        package "timeMasterSaveFiles"
        package "timeMasterSaveFilesTest"

    package "coverage"
        package "target"

    package "src"
        package "main"
            package "java"
                package "timeMaster"
            package "resources"
        package "test"
    
    package "target"



@enduml